before_commands:
    - "composer install --no-dev --prefer-source"

filter:
    excluded_paths: ["bin/*", "docs/*", "examples/*", "var/*", "vendor/*"]
checks:
    php: true
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
tools:
    external_code_coverage: false
    php_code_coverage: true
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
        filter:
            paths: ["src/*"]
    php_mess_detector:
        enabled: true
        filter:
            paths: ["src/*"]