name: "Report a bug"
title: "<NAME THE FEATURE> - <SUMMARIZE THE PROBLEM>"
description: Create a report to help us improve Phpfastcache
labels: ["Needs triage 🔎"]
assignees: ["Geolim4"]
body:
  - type: markdown
    attributes:
      value: |
        ### Before you start

        **Are you looking for development help?**
        ↩ Please note that we cannot provide assistance on web development. We recommend asking around on a dedicated help forum like StackOverflow.

        ### Issue etiquette
        
        When opening an issue, please:
        - Follow the project's [Code of Conduct](https://github.com/PHPSocialNetwork/phpfastcache/blob/master/CODE_OF_CONDUCT.md) as well as the [GitHub Community Guidelines](https://docs.github.com/en/site-policy/github-terms/github-community-guidelines).
        - Check for an [existing issue](https://github.com/PHPSocialNetwork/phpfastcache/issues) first. If someone else has opened an issue describing the same problem, please upvote their issue rather than creating another one.
        - Keep issues relevant to the project. Irrelevant issues will be automatically closed and marked as spam, and repeated offenses may result in exclusion from our organization.
        - Provide as much detail as possible. The more detail you are able to provide, the better!
        - Write issues primarily in English. While translation tools are available, we will be able to provide better assistance with pre-translated content. You are more than welcome to include a version of the issue body in your preferred language alongside the English version.
        - **Make sure that you searched an answer on our [wiki](https://github.com/PHPSocialNetwork/phpfastcache/wiki)**

        ---
  - type: dropdown
    id: type
    attributes:
      label: What type of issue is this?
      options:
        - Incorrect/unexpected/unexplainable behavior
        - Exception/Error/Warning/Notice/Deprecation
        - PSR-6/16 standard violation
        - Wiki/Documentation/Readme typo/fault or lack of documentation
        - Incompatibility (be specific)
        - Other (Please Specify)
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating system + version
      description: "The operating system with version, ex: Ubuntu 18.04 or Windows 10"
    validations:
      required: true
  - type: input
    id: php
    attributes:
      label: PHP version
      description: |
        The PHP version you're running Phpfastcache on.
        _Can be retrieved using command line `php -v | sed -n 1p`_
    validations:
      required: true
  - type: input
    id: connector
    attributes:
      label: Connector/Database version (if applicable)
      description: |
        The connector and/or SDK version + the database version if applicable, ex: 
        - Couchbase 7.1.0 + PECL Extension 3.2.2
        - Redis 7.0.0 + PECL Extension 5.3.7
        - MongoDB 5.0.2 Community + mongodb/mongodb
        - etc

        **Be as much detailed as you can be !**
    validations:
      required: false
  - type: dropdown
    id: pfc_exact_version
    attributes:
      label: Phpfastcache version
      description: |
        Please keep in mind that some versions are partially or no longer supported:
        - Phpfastcache v9 ✅ 
        - Phpfastcache v8 (Security fixes only) 🔶
        - Phpfastcache v7 (End of life) ❌
        - Phpfastcache v6 (End of life) ❌
        - Phpfastcache v5 (End of life) ❌
        - Phpfastcache >= v4 (End of life) ❌
        
        See our [global support timeline](https://github.com/PHPSocialNetwork/phpfastcache/wiki/%5BV4%CB%96%5D-Global-support-timeline) ⌚
      multiple: false
      options:
        - 9.1.3 ✅
        - 9.1.2 🔶
        - 9.1.1 ❌
        - 9.1.0 ❌
        - 9.1.0-dev ❌
        - 9.0.2 ❌
        - 9.0.1 ❌
        - 9.0.0-rc ❌
        - 9.0.0-beta5 ❌
        - 9.0.0-beta4 ❌
        - 9.0.0-beta3 ❌
        - 9.0.0-beta2 ❌
        - 9.0.0-beta ❌
        - 9.0.0-alpha3 ❌
        - 9.0.0-alpha2 ❌
        - 9.0.0-alpha ❌
        - 9.0.0-dev ❌
        - 9.0.0 ❌
        - 8.1.4 🔶
        - 8.1.3 ❌
        - 8.1.2 ❌
        - 8.1.1 ❌
        - 8.1.0 ❌
        - 8.0.8 ❌
        - 8.0.7 ❌
        - 8.0.6 ❌
        - 8.0.5 ❌
        - 8.0.4 ❌
        - 8.0.3 ❌
        - 8.0.2 ❌
        - 8.0.1 ❌
        - 8.0.0-rc2 ❌
        - 8.0.0-rc ❌
        - 8.0.0-beta ❌
        - 8.0.0-alpha ❌
        - 8.0.0-dev ❌
        - 8.0.0 ❌
        - 7.1.2 ❌
        - 7.1.1 ❌
        - 7.1.0 ❌
        - 7.0.5 ❌
        - 7.0.4 ❌
        - 7.0.3 ❌
        - 7.0.2 ❌
        - 7.0.1 ❌
        - 7.0.0-beta3 ❌
        - 7.0.0-beta2 ❌
        - 7.0.0-beta ❌
        - 7.0.0-alpha3 ❌
        - 7.0.0-alpha2 ❌
        - 7.0.0-alpha ❌
        - 7.0.0-RC4 ❌
        - 7.0.0-RC3 ❌
        - 7.0.0-RC2 ❌
        - 7.0.0-RC ❌
        - 7.0.0 ❌
        - 6.1.5 ❌
        - 6.1.4 ❌
        - 6.1.3 ❌
        - 6.1.2 ❌
        - 6.1.1 ❌
        - 6.1.0 ❌
        - 6.0.8 ❌
        - 6.0.7 ❌
        - 6.0.6 ❌
        - 6.0.5 ❌
        - 6.0.4 ❌
        - 6.0.3 ❌
        - 6.0.2 ❌
        - 6.0.1 ❌
        - 6.0.0-rc4 ❌
        - 6.0.0-rc3 ❌
        - 6.0.0-rc2 ❌
        - 6.0.0-rc1 ❌
        - 6.0.0-beta2 ❌
        - 6.0.0-beta1 ❌
        - 6.0.0-alpha2 ❌
        - 6.0.0-alpha ❌
        - 6.0.0 ❌
        - 5.0.9 ❌
        - 5.0.8 ❌
        - 5.0.7 ❌
        - 5.0.6 ❌
        - 5.0.5 ❌
        - 5.0.4 ❌
        - 5.0.3 ❌
        - 5.0.21 ❌
        - 5.0.20 ❌
        - 5.0.2 ❌
        - 5.0.19 ❌
        - 5.0.18 ❌
        - 5.0.17 ❌
        - 5.0.16 ❌
        - 5.0.15 ❌
        - 5.0.14 ❌
        - 5.0.13 ❌
        - 5.0.12 ❌
        - 5.0.11 ❌
        - 5.0.10 ❌
        - 5.0.1 ❌
        - 5.0.0-rc3 ❌
        - 5.0.0-rc2 ❌
        - 5.0.0-rc1 ❌
        - 5.0.0-beta2 ❌
        - 5.0.0-beta1 ❌
        - 5.0.0-alpha2 ❌
        - 5.0.0-alpha1 ❌
        - 5.0.0 ❌
        - 4.3.9 ❌
        - 4.3.8 ❌
        - 4.3.7 ❌
        - 4.3.6 ❌
        - 4.3.5 ❌
        - 4.3.4 ❌
        - 4.3.3 ❌
        - 4.3.2 ❌
        - 4.3.18 ❌
        - 4.3.17 ❌
        - 4.3.16 ❌
        - 4.3.15 ❌
        - 4.3.14 ❌
        - 4.3.13 ❌
        - 4.3.12 ❌
        - 4.3.11 ❌
        - 4.3.10 ❌
        - 4.3.1 ❌
        - 4.3 ❌
        - 4.2.4 ❌
        - 4.2.3 ❌
        - 4.2.2 ❌
        - 4.2.1 ❌
        - 4.1.1 ❌
        - 4.1.0 ❌
        - 4.1 ❌
        - 4.0.9 ❌
        - 4.0.8 ❌
        - 4.0.7 ❌
        - 4.0.6 ❌
        - 4.0.5 ❌
        - 4.0.4 ❌
        - 4.0.3-beta1 ❌
        - 4.0.3 ❌
        - 4.0.2beta1 ❌
        - 4.0.2-beta1 ❌
        - 4.0.2 ❌
        - 4.0.18 ❌
        - 4.0.17 ❌
        - 4.0.16 ❌
        - 4.0.15 ❌
        - 4.0.14 ❌
        - 4.0.13 ❌
        - 4.0.12 ❌
        - 4.0.11 ❌
        - 4.0.10 ❌
        - 4.0.1 ❌
        - 4.0 ❌
        - 3.1.1 ❌
        - 3.1.0 ❌
        - 3.0.9 ❌
        - 3.0.8 ❌
        - 3.0.7 ❌
        - 3.0.6 ❌
        - 3.0.5 ❌
        - 3.0.4 ❌
        - 3.0.3 ❌
        - 3.0.28 ❌
        - 3.0.27 ❌
        - 3.0.26 ❌
        - 3.0.25 ❌
        - 3.0.24 ❌
        - 3.0.23 ❌
        - 3.0.22 ❌
        - 3.0.21 ❌
        - 3.0.20 ❌
        - 3.0.2 ❌
        - 3.0.19 ❌
        - 3.0.18 ❌
        - 3.0.17 ❌
        - 3.0.16 ❌
        - 3.0.15 ❌
        - 3.0.14 ❌
        - 3.0.13 ❌
        - 3.0.12 ❌
        - 3.0.11 ❌
        - 3.0.10 ❌
        - 3.0.1 ❌
        - 3.0.0 ❌
        - 2.4.3 ❌
        - 2.4.2 ❌
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Describe the issue you're facing
      description: Provide as much detail as possible. The more detail you are able to provide, the better!
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: If applicable, please describe the behavior you expected
    validations:
      required: false
  - type: textarea
    id: code_sample
    attributes:
      label: Code sample (optional)
      description: If applicable, please provide a code sample
  - type: textarea
    id: suggestion
    attributes:
      label: Suggestion to fix the issue (optional)
      description: Do you have an suggestion on how to fix this issue ?
  - type: textarea
    id: references
    attributes:
      label: References (optional)
      description: Can you link to any release notes, bugs, pull requests, or Stack-Overflow link related to this?
  - type: textarea
    id: more_info
    attributes:
      label: Do you have anything more you want to share? (optional)
      description: For example, screenshots, screen recordings, or sample code, logs, etc.
  - type: checkboxes
    id: wiki_confirmation
    attributes:
      label: Have you searched in our Wiki before posting ?
      description: Our Wiki contains tons of information, make sure you've searched over it before posting this issue.
      options:
        - label: I have searched over the Wiki
          required: true
  - type: markdown
    attributes:
      value: |
        ---
        You're finished 👏 
        The following fields are prefilled and should not be modified. Please click **Submit new issue**.
